name: tests

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Build
      run: go build ./...

    - name: Vet
      run: go vet ./...

    - name: Test (race)
      run: go test -race ./...

    - name: Test (GOEXPERIMENT=simd)
      run: go test ./...
      env:
        GOEXPERIMENT: simd
